### ISSUE TITLE
ISSUE-key are not parsed inside commit message

### ISSUE THREAD

**Issue by claudyus** [allenta/gitlab-listener#10]
As documented in Readme the issue-key is only catch at the begin of message if #refs is not used. This behavior is undesirable.

Could you improve the parsing of issue-key inside comment?
All issues keys are composed by an uppercase project key, a dash followed by a number so it should be very easy to parse.

**Comment by carlosabalde** [comment]
Issues can be included both at the beginning of commit messages and inside commit messages using the `#refs` directive. From the documentation at https://github.com/allenta/gitlab-listener: "Users can reference multiple issues in the same commit message, separated by whitespace at the begging of the message or using the #refs directive anywhere inside the commit message."

Please, could you describe with an example what is the undesirable behaviour?

**Comment by claudyus** [comment]
I would like to use the issues name inside the commit message without using the `#refs` directive.

**Comment by carlosabalde** [comment]
I'm sorry but that's intentionally not supported. When writing a commit message you may want to mention keys of issues that you don't want to link the commit to. The list os keys you want to link the commit to needs to be more explicit, including the referenced issues at the beginning of the message or using the `#refs` directive.

**Comment by mindcreations** [comment]
If I'm not wrong Atlassian Fisheye works as reported by claudyus for SVN comment commits, ie takes the issuekey from anywhere in the comment without special directives.
I can see that you wanted to do a more sophisticated mechanism to handle issue keys but maybe an option to configure this behaviour on Gitlab Listener could be the compromise between the two approaches. Some checkbox like:

[X] Consider issue keys as #refs even without the #refs directive

**Comment by carlosabalde** [comment]
The described behaviour can be implemented trivially, but it's intentionally not supported in order to keep things simple. Let's see if more people out there feel this is a nice enhancement for the add-on. If so, I'll try to have this ready as soon as possible :)

Thanks a lot for your feedback.

**Comment by mindcreations** [comment]
My point of view is that is more complex to remember to add #refs on every commit rather that having to type only the issue keys, anywhere in the comment. So, to keep things simple as you said, maybe I should rephrase what I suggested, the checkbox should be something like:

[  ] Do not consider issue keys outside #refs directive

So the default simple behaviour will be the one suggested by claudyus (that should be the default for Atlassian repositories like Fisheye or Stash) and the more sophisticated one is the one suggested by you.

Sincerely, isn't simpler to say: 

"put the issue keys anywhere in the comment" 

rather than 

"put the issue key at the beginning of the comment or, if you need to type it after the beginning, put a #refs directive followed by issue keys; other keys mentioned before the #refs directive will be ignored"?

**Comment by carlosabalde** [comment]
This feature is now available in GitLab Listener [1.2.1](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b100200100) (JIRA 6.x) and [2.0.1](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b200000100) (JIRA 7.x). Thanks!
