### ISSUE TITLE
Showing GIT activity on comments tab

### ISSUE THREAD

**Issue by suranga** [allenta/gitlab-listener#23]
Hi Support,

We recently purchase gitlab-listener. is there any way to showing git activity on comments tab instead activity tab on issues in jira. appreciate your early response on this matter.

Thanks & regards,
suranga@intervest.gi
License SEN : SEN-5283672

**Comment by carlosabalde** [comment]
Hi,

You can set up that in the add-on settings. If the 'Use activities instead of comments' option is checked, pushed commits will be logged in the activity tab. Otherwise, commits will be logged in the comments tab. 

Anyway, beware that adding a comment to an issue is considered by JIRA as an activity. Therefore, when the 'Use activities instead of comments' option is unchecked, comments generated by the add-on will also be logged by JIRA as activities in the activity tab.
