### ISSUE TITLE
Email aliases for users

### ISSUE THREAD

**Issue by infernix** [allenta/gitlab-listener#31]
It would be nice if it were possible to set up e-mail aliases for git commits to match JIRA users.

Could be done by adding this inside the addon as a simple CSV list of addresses mapping to a jira user, or by adding an extra Custom field (EmailAliases) to JIRA users and looking up addresses there.

**Comment by carlosabalde** [comment]
I'm not sure if this would be useful in many scenarios, but it's a simple addition. I can't promise any dates but the feature will be considered.

**Comment by asfaltboy** [comment]
I'd like to point out that this is important, because when (occasionally) a user commits with an alias email, gitlab-listener may log this as another user in jira.

Also, Gitlab supports adding multiple (alias) emails for a user, and [returning these is documented in the API](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/users.md#list-emails). I expected the add-on to know of this mapping and use the correct JIRA user.

**Comment by carlosabalde** [comment]
The users mapping feature is now available in GitLab Listener [1.2.7](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b100200700) (JIRA 6.x) and [2.0.7](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b200000700) (JIRA 7.x).

This is not implemented using the GitLab API. I wanted to keep it simple and flexible. In the add-on settings page now you can set up the mapping as a list of tuples, each one containing an e-mail address and a JIRA username. For example:

```
bob@foo.com, bob
alice@foo.com, alice
alice@bar.com, alice
```

If the e-mail address associated to a commit message (e.g. `alice@bar.com`) does not match any JIRA user (e.g. Alice's e-mail address at JIRA is `alice@example.com`) the mapping will be used. If nothing is found in the mapping, then the fallback users will be used.

Thanks!
