### ISSUE TITLE
#action not updating Jira issue status

### ISSUE THREAD

**Issue by EvinGit** [allenta/gitlab-listener#33]
Hi carlosabalde:
    I have configured this plugin for jira and gitlab as per the documentation provided in https://github.com/allenta/gitlab-listener/blob/master/README.md. when I run "git commit -m 'TEST-1 #action close issue' ", it is invalid, but I can see some info that have committed in jira, such as: 

```
evin  pushed changeset to GitLab on TEST-4
Changeset 1232586872068b085d47c5b6b50655e05ba2ce74
    TEST-4 #action close issue
```

   I need your help, thanks!

**Comment by carlosabalde** [comment]
The commit message looks valid to me. Perhaps the `#action` part is not valid, but the commit looks valid and therefore is logged in JIRA.

**Comment by EvinGit** [comment]
I have logged in JIRA and GitLab, our company's JIRA is the Chinese version, it exists some possible for not supporting?

**Comment by EvinGit** [comment]
I think  that the documentation provided in https://github.com/allenta/gitlab-listener/blob/master/README.md is less, can you support more detailed documentation？Thank you very much!

**Comment by EvinGit** [comment]
carlosabalde, the Jira's workflow is there any requirement?  I open debug log, but I don't know where to see, client? or server ? I am sorry for asking simple question because of  the jira server is not configured by me.

**Comment by EvinGit** [comment]
carlosabalde, the Jira's workflow is there any requirement? I open debug log, but I don't know where to see, client? or server ? I am sorry for asking simple question because of the jira server is not configured by me.
Moreover, our company uses the version of the add-on: 1.2.6 (JIRA 6.4.12) , #action is been supported by JIRA(>=7.0)?

**Comment by carlosabalde** [comment]
I confirm your version of the add-on supports the `#action` directive. When using this directive you need to include the name of the action as shown in the workflow diagram and the user associated to the commit needs some permissions.

In order to know what's going on I'd suggest enable debug level and check the JIRA log (usually located in `/opt/atlassian/jira/logs/catalina.out`). Please, follow the steps below:
1. Enable debug level:
   1. Log in as an user with the 'JIRA System Administrators' global permission.
   2. Choose 'System'. Then select 'Troubleshooting and Support > Logging & Profiling' to open the Logging page.
   3. Scroll to the 'Default Loggers' section and click 'Configure logging level for another package'.
   4. Package name is `com.allenta.jira.plugins.gitlab.listener.Servlet`.
2. Push a couple of commits to GitLab including the `#action` directive while checking the output in the JIRA log.
3. If unsure about the problem, copy & paste here what you have seen in the JIRA log. Hopefully the explanation to your issue will be in there.
4. Disable debug level reverting previous changes.

**Comment by EvinGit** [comment]
So sad! I have no permission to view the log, but thanks a lot for your reply.

**Comment by EvinGit** [comment]
![CSDN图标](C:\用户\Administrator\桌面\1.png)

**Comment by schnepp** [comment]
I am having the same issue. In the log file I find this statement:
Failed to execute JIRA workflow action: a matching action was not found
The action statement used was: "#action close issue, fixed" as shown on the webpage. Can you please advise?
Is there a comprehensive list of possible actions?

**Comment by carlosabalde** [comment]
Possible actions depend on the workflow associated to the project of the issue referenced in the commit message. Possible actions also depend of the current state of the issue. Could you share a screenshot of the workflow as well as the current state of the issue?

**Comment by schnepp** [comment]
Thank you. Choosing any of the actions of the workflow works. Solved.
