### ISSUE TITLE
Problems with an #action comment

### ISSUE THREAD

**Issue by mcapitanio** [allenta/gitlab-listener#43]
Hi,
we are evaluating the add-on with a Jira 7.2 installation, but we are having problems.
We are using a workflow base on the "Scrum Workflow Scheme For Jira Projects" found on the Marketplace. We created a new "User Story" issue named with "GALCOV-3" with the workflow and configured the GitLab project with the Webhook.

When we Commit a change using the following comment:

```
GALCOV-3 #action start
```

or:

```
GALCOV-3 #action start-progress
```

we get the following error in Jira:

```
2016-09-29 08:50:56,358 http-nio-80-exec-11 ERROR MCAPITANIO 530x6582x1 - 192.168.1.45 /plugins/servlet/gitlab/listener [c.a.j.p.gitlab.listener.Servlet] Failed to execute JIRA workflow action: a matching action was not found (https://gitlab.cdp.it/galileo-covenant/galileo-covenant-ui/commit/b22872e9de77a20e9974f78168a7a12fe216f4bc).
```

**Comment by mcapitanio** [comment]
I have found that if I write the action including the space:

```
GALCOV-3 #action start progress
```

it works.

I was confused with the use of Smart Commits in Jira which works even if I use the first word before the space as action id.
But why don't you unify the action behaviour?

**Comment by carlosabalde** [comment]
I was provisioning a test server in order to reproduce this when I got your last message. Glad to see you've been able to solve the problem on your own.

At the moment the add-on explores the workflow looking for actions IDs matching the exact value provided in the `#action` directive. I agree an approximate string matching would be useful, but that's currently not available.
