### ISSUE TITLE
Unable to upload Addon to Jira

### ISSUE THREAD

**Issue by ashimmishra** [allenta/gitlab-listener#5]
I tried to upload the addon using the url:
https://marketplace.atlassian.com/download/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/version/100100400

![image](https://cloud.githubusercontent.com/assets/12443661/7630502/379d8bce-fa54-11e4-84f7-3449c156db37.png)

But it threw an error. Can you please help out.

**Comment by carlosabalde** [comment]
Hi,

A couple of questions:
- What version of JIRA are you using?
- Why using the 'Upload add-on' feature instead of 'Find new add-ons'?

Thanks.

**Comment by ashimmishra** [comment]
Hi,

I am using JIRA v6.5-OD-03-002.
Its hosted on Atlassian.
I wasn't able to search for Gitlab listener in Find add-ons.

**Comment by carlosabalde** [comment]
You probably were not able to find the add-on using the 'Find new add-ons' feature because JIRA is filtering it out. The GitLab Listener add-on requires JIRA ≥ 6.3 and ≤ 6.4.4. Additionally, I'm not sure if you would be able to install it in a hosted JIRA. I'm afraid you're not going to be able to use it. Sorry!
