### ISSUE TITLE
Data Center compatible?

### ISSUE THREAD

**Issue by svante66** [allenta/gitlab-listener#62]
Hey guys,
Do you have any plans making your plugin DC compatible? 
More and more customers are migrating to JIRA Data Center and it would be great if your plugin is marked as compatible with a multi-server setup

Thnx in advance!
Cheers,
// Svante

**Comment by carlosabalde** [comment]
Hi @svante66! To be honest, we don’t have any plans for DC support, but we’ll try to find the time at least to evaluate viability and measure the required effort. No promises at all though. We’ll keep this open while waiting for a final decision.

**Comment by svante66** [comment]
Hey Carlos,
Thnx for your prompt reply! I appreciate it a lot!
I will shelf this my self in the meantime. Hope to hear from you again when/if you find time to verify this.
Cheers,
// Svante

**Comment by carlosabalde** [comment]
Hi @svante66. We've been analysing this. Adding support for Jira Cloud is a completely new beast that requires a full rewrite and integration with the Atlassian Connect framework. Since building Jira add-ons is completely unrelated with our core business (the GitLab Listener add-on was originally created for our internal usage), we've decided to cancel cloud support. Sorry!

**Comment by dafriis** [comment]
I don't know if issues like these can be re-opened or if I should create a new issue but now two years later Atlassian has dropped support for server and everyone is forced to switch to at least Data Center. Is the plugin still compatible in some way or will you also stop using your own plugin?

**Comment by carlosabalde** [comment]
We are not adding support for Data Center. It'd be trivial to do that, but Atlassian requires a certification process in order to publish Data Center ready plugins that is simply too much. On the other hand, we are also no planning to create a Cloud version because a better plugin directly provided by GitLab is already available. Hope this helps!
